FROM amazoncorretto:11
ENV JAR_NAME=F1Discord-Bot-all.jar
ENV HOME_DIR=/app
ARG DISCORD_TOKEN
ENV DISCORD_TOKEN='${DISCORD_TOKEN}'
WORKDIR $HOME_DIR
COPY /build/libs/$JAR_NAME $HOME_DIR

ENTRYPOINT exec java -jar $HOME_DIR/$JAR_NAME $DISCORD_TOKEN indev