version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  gradle: circleci/gradle@3.0.0
jobs:
  gradle-build:
    docker:
      - image: cimg/openjdk:11.0.18
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout # Checkout the repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle fatJar
workflows:
    build-deploy:
      jobs:
        - gradle/run:
            filters:
              branches:
                only:
                  - master
        - aws-ecr/build-and-push-image:
            requires:
              - gradle/run
            assume-web-identity: true 
            attach-workspace: false 
            checkout: true 
            create-repo: true 
            docker-login: false 
            no-output-timeout: '3'  
            public-registry: false 
            push-image: true 
            remote-docker-layer-caching: false 
            repo: f1discordbot 
            repo-scan-on-push: true 
            role-arn: arn:aws:iam::842735713588:role/CirclePipelineIAM
            set-repo-policy: false 
            setup-remote-docker: false 
            skip-when-tags-exist: false
            context: aws