version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  gradle-build:
    docker:
      - image: cimg/openjdk:11.0.18
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout # Checkout the repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build --no-daemon
      - persist_to_workspace:
          root: build/libs
          paths:
            - "F1Discord-Bot-all.jar"
      - persist_to_workspace:
          root: .
          paths:
            - "Dockerfile"
workflows:
    build-deploy:
      jobs:
        - gradle-build:
            filters:
              branches:
                only:
                  - master
        - aws-ecr/build-and-push-image:
            pre-steps:
              - attach_workspace:
                  at: build/libs
              - attach_workspace:
                  at: .
            checkout: false
            dockerfile: Dockerfile
            assume-web-identity: true
            region: '${AWS_DEFAULT_REGION}'
            registry-id: AWS_ECR_REGISTRY_ID
            extra-build-args: "--compress --build-arg DISCORD_TOKEN=$DISCORD_TOKEN --build-arg VER=$CIRCLE_SHA1"
            create-repo: true
            no-output-timeout: '3m' 
            push-image: true 
            repo: f1discordbot
            repo-scan-on-push: true
            role-arn: arn:aws:iam::842735713588:role/CIRole
            role-session-name: CIRole
            context: aws                                          