name: Gradle Build
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

      - name: Move Jar file
        run: mv build/libs/F1Discord-Bot-all.jar F1Discord-bot-all.jar

      - name: Upload Fat Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: F1Discord-bot-all.jar